#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/57a40c50-11c7-4f92-ab17-6155b9ef2e7a 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch fan;
  CloudSwitch led1;
  CloudSwitch buzzer;
  CloudTemperatureSensor temperature;
  float humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


//#define GAS 16
#define LED 5
#define FAN 12
#define BUZ 14

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  //pinMode(GAS,INPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  pinMode(FAN,OUTPUT);
  pinMode(LED,OUTPUT);
  pinMode(BUZ,OUTPUT);
 // flame=digitalRead(GAS);
  
}



void onFanChange() {
  // Do something
    if(fan){
    digitalWrite(FAN, HIGH);
  }
  else{
    digitalWrite(FAN, LOW);
  }
}



void onLed1Change() {
  // Do something
    if(led1){
    digitalWrite(LED, HIGH);
  }
  else{
    digitalWrite(LED, LOW);
  }
}



void onBuzzerChange() {
  // Do something
    if(buzzer){
    digitalWrite(BUZ, HIGH);
  }
  else{
    digitalWrite(BUZ, LOW);
  }
  
}

/*
void onColorChange() {
  // Do something
}*/




